<?php
session_start();

if (!isset($_SESSION['role']) || !in_array($_SESSION['role'], ['admin','employee'])) {
    exit("Access denied");
}

$conn = new mysqli("localhost", "root", "", "electricity_db");

$meter_no = $conn->real_escape_string($_POST['meter_id']);
$units = (float)$_POST['units'];

$result = $conn->query("SELECT * FROM consumers WHERE meter_id='$meter_no'");

if ($result->num_rows == 0) {
    echo "<p style='color:red; text-align:center;'>Invalid Meter ID</p>";
    exit();
}

$user = $result->fetch_assoc();

$bill = 0;
if ($units <= 50) {
    $bill = $units * 1;
} elseif ($units <= 100) {
    $bill = 50*1 + ($units-50)*1.5;
} else {
    $bill = 50*1 + 50*1.5 + ($units-100)*2;
}

$conn->query(
    "INSERT INTO bills (meter_id, units, amount, generated_by)
     VALUES ('$meter_no', $units, $bill, '{$_SESSION['role']}')"
);

echo "
<div class='bill-box'>
    <h2>Electricity Bill</h2>
    <hr>
    Name: {$user['name']}<br>
    Mobile: {$user['mobile']}<br>
    Address: {$user['address']}<br>
    Meter No: {$meter_no}<br>
    Units Consumed: {$units}<br>
    <hr>
    <h3>Total Amount: ₹$bill</h3>
    <p>Generated by: ".ucfirst($_SESSION['role'])."</p>
</div>
";
